In [1]:
import numpy as np

In [17]:
data1 = np.array([1,2,3,4,5])
print(data1)

data2 = np.array([[1,2],[3,4],[5,6]])
print(data2)
print(data2.shape)
#单位矩阵和空矩阵
print(np.zeros([2,2]),np.ones([3,3]))


#修改矩阵内容
data2[1,0] = 10
print(data2)

#常量基本运算+-*/
data3 = np.ones([2,3])
print(data3*2)

#矩阵运算
data4 = np.array([[1,2,3],[4,5,6]])
print(data3+data4)
print(data3*data4)


[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[0. 0.]
 [0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 1  2]
 [10  4]
 [ 5  6]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[2. 3. 4.]
 [5. 6. 7.]]
[[1. 2. 3.]
 [4. 5. 6.]]
